server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: test # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://test # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/test/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: report
          uri: lb://report
          predicates:
            - Path=/report/**
        - id: guidebook
          uri: lb://guidebook
          predicates:
            - Path=/guidebook/**
        - id: laboratory
          uri: lb://laboratory
          predicates:
            - Path=/laboratory/**
        - id: todo
          uri: lb://todo
          predicates:
            - Path=/todo/**
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
        - id: login
          uri: lb://login
          predicates:
            - Path=/login/**
        - id: course
          uri: lb://course
          predicates:
            - Path=/course/**
        - id: grade
          uri: lb://grade
          predicates:
            - Path=/grade/**
        - id: login
          uri: lb://login
          predicates:
            - Path=/login/**
        - id: bulletin
          uri: lb://bulletin
          predicates:
            - Path=/bulletin/**
      #          filters:
#            - AddRequestHeader=Truth, hd is lj # 添加请求头
#        新增网关路由在这里注册
#        - id: course # 路由id，自定义，只要唯一即可
#          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
#          uri: lb://course # 路由的目标地址 lb就是负载均衡，后面跟服务名称
#          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
#            - Path=/course/** # 这个是按照路径匹配，只要以/user/开头就符合要求
##            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # 同意所有，当然在vue项目中可以换成vue项目的地址，例如
#            allowedOrigins:
#              - "localhost://*"
#              - "localhost://8080"
#              - "localhost://8082"
#              - "http://localhost:8082"
#              - "http://*.guisu.website"
#              - "https://*.guisu.website"
#              - "http://8.131.225.65"
#              - "https://8.131.225.65"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        - AddRequestHeader=Truth, this is a spring cloud proj # 添加请求头
