server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://124.220.67.187:3306/zy_test?useSSL=false
    username: root
    password: YuRan2022
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: todo
  cloud:
    nacos:
      server-addr: localhost:8848

mybatis:
  type-aliases-package: cn.edu.tongji.backend.todo.pojo
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  level:
    cn.edu.tongji.backend: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka